### ISSUE TITLE
Gallery app crash

### ISSUE THREAD

**Issue by garfieldnate** [fabulous-dev/Fabulous.Avalonia#58]
Given that the repo is marked WIP, apologies if you didn't want any bugs reported yet!

***

Run the gallery sample project using `dotnet run --framework net7.0`. If you click any page besides `AutoCompleteBox`, and then click `AutoCompleteBox`, you hit an `ArgumentOutOfRangeException` at `Fabulous.Avalonia.Attributes` line 116 (`let childNode = node.TreeContext.GetViewNode(box targetColl.[index])`). I printed out the values and found that `index` was 0 and `targetColl.Count` was also 0. Here's the stack trace:

```
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Avalonia.Collections.AvaloniaList`1.get_Item(Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 150
   at Fabulous.Avalonia.Attributes.applyDiff@88T.Invoke(a _arg1, WidgetCollectionItemChanges diffs, IViewNode node) in /Users/nathanglenn/dev/workspaces/dotNET_workspace/Fabulous.Avalonia/src/Fabulous.Avalonia/Attributes.fs:line 118
   at Fabulous.ViewNode.Fabulous.IViewNode.ApplyDiff(WidgetDiff& diff)
   at Fabulous.Avalonia.Attributes.applyDiff@88T.Invoke(a _arg1, WidgetCollectionItemChanges diffs, IViewNode node) in /Users/nathanglenn/dev/workspaces/dotNET_workspace/Fabulous.Avalonia/src/Fabulous.Avalonia/Attributes.fs:line 120
   at Fabulous.ViewNode.Fabulous.IViewNode.ApplyDiff(WidgetDiff& diff)
   at Fabulous.Avalonia.Attributes.applyDiff@88T.Invoke(a _arg1, WidgetCollectionItemChanges diffs, IViewNode node) in /Users/nathanglenn/dev/workspaces/dotNET_workspace/Fabulous.Avalonia/src/Fabulous.Avalonia/Attributes.fs:line 120
   at Fabulous.ViewNode.Fabulous.IViewNode.ApplyDiff(WidgetDiff& diff)
   at Fabulous.Avalonia.ContentControl.ContentWidget@13.Invoke(WidgetDiff diff, IViewNode node)
   at Fabulous.ViewNode.Fabulous.IViewNode.ApplyDiff(WidgetDiff& diff)
   at Fabulous.Avalonia.ContentControl.ContentWidget@13.Invoke(WidgetDiff diff, IViewNode node)
   at Fabulous.ViewNode.Fabulous.IViewNode.ApplyDiff(WidgetDiff& diff)
   at Fabulous.Avalonia.Attributes.applyDiff@88T.Invoke(a _arg1, WidgetCollectionItemChanges diffs, IViewNode node) in /Users/nathanglenn/dev/workspaces/dotNET_workspace/Fabulous.Avalonia/src/Fabulous.Avalonia/Attributes.fs:line 120
   at Fabulous.ViewNode.Fabulous.IViewNode.ApplyDiff(WidgetDiff& diff)
   at Fabulous.Avalonia.ContentControl.ContentWidget@13.Invoke(WidgetDiff diff, IViewNode node)
   at Fabulous.ViewNode.Fabulous.IViewNode.ApplyDiff(WidgetDiff& diff)
   at Fabulous.Avalonia.ApplicationUpdaters.mainWindowApplyDiff(WidgetDiff diff, IViewNode node) in /Users/nathanglenn/dev/workspaces/dotNET_workspace/Fabulous.Avalonia/src/Fabulous.Avalonia/Widgets/Application.fs:line 67
   at Fabulous.Avalonia.Application.MainWindow@98.Invoke(WidgetDiff diff, IViewNode node)
   at Fabulous.ViewNode.Fabulous.IViewNode.ApplyDiff(WidgetDiff& diff)
   at Fabulous.Reconciler.update(FSharpFunc`2 canReuseView, FSharpValueOption`1 prevOpt, Widget next, IViewNode node)
   at Fabulous.ViewAdapters.OnStateChanged@222.Invoke(Unit unitVar0)
   at Fabulous.Avalonia.Program.statefulWithCmd@85-4.Invoke()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 193
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 39
   at Avalonia.Native.Interop.Impl.__MicroComIAvnSignaledCallbackVTable.Signaled(Void* this, Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/Interop.Generated.cs:line 4586
--- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 90
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at Gallery.Desktop.Program.main(String[] argv) in /Users/nathanglenn/dev/workspaces/dotNET_workspace/Fabulous.Avalonia/samples/Gallery/Platform/Desktop/Program.fs:line 20
```

**Comment by edgarfgp** [comment]
Thanks for the issue report :). I think is due to the  `Task.Delay` I had in the last AutoCompleteBox using the async pupulator.
I just removed that. @garfieldnate  Could you give it a try again with the latest changes? Thanks

**Comment by garfieldnate** [comment]
No problem :) I pulled the latest and the bug is still there. Sorry I can't provide more insight here, as I'm an absolute F# newbie.

**Comment by edgarfgp** [comment]
No worries :) . Are you using a windows or mac machine ?

**Comment by garfieldnate** [comment]
macOS 13.1. It's an M1.

**Comment by edgarfgp** [comment]
Is still crashing if you comment out this line https://github.com/fabulous-dev/Fabulous.Avalonia/blob/59baaa534025bf0c22664beda7fd3f142de69b78/samples/Gallery/Widgets/AutoCompleteBox.fs#L78 ?

**Comment by ConradRoesch** [comment]
I can replicate this on Windows 11 (v. 22H2).

The crash is not caused by the AutoCompleteBox instances, but by the TextBlock().textInlines. The following block appears to be causing the crash (with or without the presence of the AutoCompleteBox controls):
 
https://github.com/fabulous-dev/Fabulous.Avalonia/blob/59baaa534025bf0c22664beda7fd3f142de69b78/samples/Gallery/Widgets/AutoCompleteBox.fs#L53-L65

**Comment by edgarfgp** [comment]
Yeah there is a BUG in the textInlines and how we do the View diffing in that scenario . I will have look during the week :)
